// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/qwen.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const QWEN_MODELS: ChatModelCatalog<typeof values, "qwen"> =
	flattenChatModelCatalog("qwen", values);

export const QWEN_IMAGE_MODELS: ImageModelCatalog<typeof values, "qwen"> =
	flattenImageModelCatalog("qwen", values);

export const QWEN_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "qwen"> =
	flattenClassifierModelCatalog("qwen", values);
